---
namespace: "eliminyro"
name: "samba"
version: 0.1.0
description: "An Ansible role to deploy a Samba server and mount shares"
readme: "README.md"
authors:
  - "Pavel Eliminyro"
license:
  - "GPL-3.0-or-later"
repository: "https://github.com/eliminyro/eliminyro.samba"
issues: "https://github.com/eliminyro/eliminyro.samba/issues"
tags:
  - "samba"
  - "cifs"
  - "ansible"
  - "linux"
dependencies:
  ansible.posix: ">=1.6.2"
build_ignore:
  - ".git"
  - ".github"
  - ".gitignore"
  - ".ansible-lint"
  - ".yamllint"
  - ".ansible"
  - ".vscode"
  - "molecule"
  - "tests"
  - "files"
  - "*.pyc"
  - "__pycache__"
  - ".DS_Store"
