---

mount_credentials:
  default:
    username: "username"
    password: "password"

mount_dirs: []

mount_opts: "credentials=/etc/.smbcred,vers=3.1.1"
mount_used_creds: "{{ mount_dirs | map(attribute='credentials') | unique | list }}"
